spring:
  datasource:
    url: jdbc:h2:mem:${testdb};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
  data:
    redis:
#      host: localhost
      host: 127.0.0.1
      port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: ${port}

quartz:
  cron:
    expression: "0/10 * * * * ?" # 10초마다 실행되는 Cron 표현식

logging:
  level:
    root: INFO
    org.springframework.batch: DEBUG
